services:
  - type: web
    name: nigerian-graduate-salary-api
    env: python
    plan: free
    buildCommand: cd summative/API && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd summative/API && uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: "3.11.0"
