services:
  - type: web
    name: nigerian-salary-predictor-api
    env: python
    plan: free
    rootDir: summative/API
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
