services:
  - type: web
    name: nigerian-graduate-salary-api
    env: python
    rootDir: ./summative/API
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
